# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shared-secret-authentication}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Moore"]
  s.date = %q{2011-01-20}
  s.description = %q{helper methods to make shared secret authentication easier}
  s.email = %q{joshsmoore@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "config/shared_secret.yml",
    "lib/shared-secret-authentication.rb",
    "lib/shared-secret-authentication/generator.rb",
    "lib/shared-secret-authentication/hash_signatures.rb",
    "lib/shared-secret-authentication/load_secret.rb",
    "shared-secret-authentication.gemspec",
    "spec/shared-secret-authentication/generator_spec.rb",
    "spec/shared-secret-authentication/hash_signatures_spec.rb",
    "spec/shared-secret-authentication/load_secret_spec.rb",
    "spec/shared-secret-authentication_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "watchr.rb"
  ]
  s.homepage = %q{http://github.com/joshsmoore@gmail.com/shared-secret-authentication}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{helper methods to make shared secret authentication easier}
  s.test_files = [
    "spec/shared-secret-authentication/generator_spec.rb",
    "spec/shared-secret-authentication/hash_signatures_spec.rb",
    "spec/shared-secret-authentication/load_secret_spec.rb",
    "spec/shared-secret-authentication_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

