# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shared-secret-authentication}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Moore"]
  s.date = %q{2010-11-03}
  s.description = %q{helper methods to make shared secret authentication easier}
  s.email = %q{joshsmoore@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config/shared_secret.yml",
     "lib/shared-secret-authentication.rb",
     "lib/shared-secret-authentication/hash_signatures.rb",
     "lib/shared-secret-authentication/load_secret.rb",
     "shared-secret-authentication.gemspec",
     "spec/shared-secret-authentication/hash_signatures_spec.rb",
     "spec/shared-secret-authentication/load_secret_spec.rb",
     "spec/shared-secret-authentication_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "watchr.rb"
  ]
  s.homepage = %q{http://github.com/joshsmoore@gmail.com/shared-secret-authentication}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{helper methods to make shared secret authentication easier}
  s.test_files = [
    "spec/shared-secret-authentication/hash_signatures_spec.rb",
     "spec/shared-secret-authentication/load_secret_spec.rb",
     "spec/shared-secret-authentication_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

